/**
 * Storage provider interface.
 *
 * Everything the app "stores" outside the DB — property images, KYC
 * documents, PDF invoices — goes through this interface. Implementations
 * must NOT allow direct unrestricted bucket access; the API always signs
 * URLs on behalf of an authenticated caller.
 *
 * Rules honoured by every implementation:
 *   - `private` visibility is the default; `public` requires an explicit override
 *   - Content-type MUST be on the allowlist for the declared `kind`
 *   - Object sizes above `MAX_UPLOAD_BYTES` are refused server-side
 *   - Filenames are always generated by the provider (never user-supplied)
 */

export type MediaKind = 'image' | 'video' | 'document';
export type Visibility = 'private' | 'public';

export const MAX_UPLOAD_BYTES = 25 * 1024 * 1024; // 25 MB — refuse anything larger

/** MIME allowlist per kind — server rejects anything outside this list. */
export const ALLOWED_CONTENT_TYPES: Record<MediaKind, string[]> = {
  image:    ['image/jpeg', 'image/png', 'image/webp', 'image/heic'],
  video:    ['video/mp4', 'video/quicktime'],
  document: ['application/pdf'],
};

export interface SignedUploadRequest {
  ownerUserId: string;
  propertyId?: string;
  kind: MediaKind;
  contentType: string;
  sizeBytes: number;
  sha256: string;
  visibility?: Visibility;
}

export interface SignedUploadResult {
  assetId: string;
  provider: string;
  providerKey: string;
  /** Client PUTs the file here directly. Short-lived. */
  uploadUrl: string;
  method: 'PUT' | 'POST';
  headers?: Record<string, string>;
  expiresAt: Date;
}

export interface SignedDownloadResult {
  assetId: string;
  url: string;
  expiresAt: Date;
}

export interface StorageProvider {
  readonly name: string;
  /** Malware-scanning hook. Implementations may forward to ClamAV / VirusTotal. */
  readonly malwareScannerHook?: (providerKey: string) => Promise<void>;

  signUpload(input: SignedUploadRequest): Promise<SignedUploadResult>;
  signDownload(providerKey: string, ttlSeconds?: number): Promise<SignedDownloadResult>;
}

// ---------------- Validation helpers (shared by all providers) ----------------

export function assertUploadShape(input: SignedUploadRequest): void {
  if (input.sizeBytes <= 0) throw new Error('sizeBytes must be positive');
  if (input.sizeBytes > MAX_UPLOAD_BYTES) {
    throw new Error(`file too large: ${input.sizeBytes} > ${MAX_UPLOAD_BYTES}`);
  }
  const allow = ALLOWED_CONTENT_TYPES[input.kind];
  if (!allow.includes(input.contentType)) {
    throw new Error(`contentType ${input.contentType} not allowed for kind=${input.kind}`);
  }
  if (!/^[0-9a-f]{64}$/i.test(input.sha256)) {
    throw new Error('sha256 must be 64 hex chars');
  }
}
